global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: [ "localhost:8085" ]

  - job_name: "backend"

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets: [ "host.docker.internal:8081" ]
        labels:
          namespace: conversion-service
