{
 "title": "Java Virtual Machine",
 "tags": [ "jvm" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (jvm_classes_loaded_classes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (delta(jvm_classes_loaded_classes{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum (jvm_memory_used_bytes{})", "legendFormat": "used" },
    {
     "expr": "sum (jvm_memory_committed_bytes{})",
     "legendFormat": "committed"
    },
    { "expr": "sum (jvm_memory_max_bytes{})", "legendFormat": "max" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{ area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_memory_committed_bytes{  area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum (jvm_memory_max_bytes{  area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_memory_committed_bytes{area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum (jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (jvm_threads_live_threads{})",
     "legendFormat": "live"
    },
    {
     "expr": "sum (jvm_threads_daemon_threads{})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum (jvm_threads_peak_threads{})",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Threads by State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (jvm_threads_states_threads{})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (process_files_open_files{})",
     "legendFormat": "open"
    },
    {
     "expr": "sum (process_files_max_files{})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Pools: Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers (size)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_buffer_memory_used_bytes{id=\"direct\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_buffer_total_capacity_bytes{id=\"direct\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers (count)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (jvm_buffer_count_buffers{id=\"direct\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped Buffers (size)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_buffer_memory_used_bytes{id=\"mapped\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_buffer_total_capacity_bytes{id=\"mapped\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers (count)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (jvm_buffer_count_buffers{id=\"mapped\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Memory Pools: Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_memory_committed_bytes{id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum (jvm_memory_max_bytes{id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Pools: Non-Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (jvm_memory_committed_bytes{id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum (jvm_memory_max_bytes{id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(jvm_gc_memory_allocated_bytes_total{}[$__rate_interval]))",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum (rate(jvm_gc_memory_promoted_bytes_total{}[$__rate_interval]))",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (action,cause) (rate(jvm_gc_pause_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (action,cause) (rate(jvm_gc_pause_seconds_sum{}[$__rate_interval]))\n/\nsum by (action,cause) (rate(jvm_gc_pause_seconds_count{}[$__rate_interval]))",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "sum by (action,cause) (jvm_gc_pause_seconds_max{})",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  }
 ]
}